"""
Static historical geomagnetic storm archive.
Sources: NOAA SWPC, NASA, ESA space weather archives.
"""

HISTORICAL_STORMS = [
    {
        "id": "carrington-1859",
        "date": "1859-09-01",
        "name": "Carrington Event",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 48,
        "affectedRegions": ["US Northeast", "Western Europe", "Scandinavia", "Western Russia"],
        "economicImpact": "~$10T (modern estimate)",
        "description": "The most powerful geomagnetic storm on record. Telegraph systems worldwide failed and caught fire. Auroras were visible as far south as Cuba and Hawaii. A repeat today would cause catastrophic grid damage estimated at $0.6–2.6 trillion in the US alone.",
    },
    {
        "id": "march-1989",
        "date": "1989-03-13",
        "name": "March 1989 Quebec Blackout",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 12,
        "affectedRegions": ["Quebec Grid", "Ontario Grid", "US Northeast", "Scandinavia"],
        "economicImpact": "$2B (1989 USD)",
        "description": "A G5 storm caused the complete collapse of Hydro-Québec's power grid in 92 seconds, leaving 6 million people without power for up to 9 hours. Over 200 power grid problems were reported across North America. The storm was caused by a CME ejected March 9–10.",
    },
    {
        "id": "halloween-2003",
        "date": "2003-10-28",
        "name": "Halloween Storms",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 72,
        "affectedRegions": ["Scandinavia", "UK National Grid", "US Northeast", "Japan Eastern Grid"],
        "economicImpact": "$1.5B",
        "description": "A series of X-class solar flares and CMEs between Oct 19 – Nov 5 produced multiple G4–G5 storms. Sweden suffered a one-hour blackout affecting 50,000 people. Over 47 power transformers were damaged in South Africa. Several satellites were lost or degraded.",
    },
    {
        "id": "may-2024",
        "date": "2024-05-10",
        "name": "Gannon Storm (May 2024)",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 36,
        "affectedRegions": ["US Northeast", "US Midwest", "UK National Grid", "Scandinavia", "Western Russia"],
        "economicImpact": "$100M (estimated)",
        "description": "The strongest geomagnetic storm since 2003, named the Gannon Storm after space weather scientist Jennifer Gannon. Auroras were visible across much of North America and Europe. Multiple grid operators issued emergency alerts; minor transformer heating was reported in several US states.",
    },
    {
        "id": "july-2000",
        "date": "2000-07-14",
        "name": "Bastille Day Event",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 24,
        "affectedRegions": ["Japan Eastern Grid", "US Northeast", "Scandinavia", "UK National Grid"],
        "economicImpact": "$500M",
        "description": "A major X5.7 solar flare on Bastille Day triggered an extreme geomagnetic storm. Japan's ASCA satellite was permanently disabled. High-frequency radio communications were disrupted globally for several hours. Power companies across North America reported voltage irregularities.",
    },
    {
        "id": "sept-2017",
        "date": "2017-09-07",
        "name": "September 2017 X9.3 Flare",
        "category": "G4",
        "peakKp": 8.2,
        "durationHours": 18,
        "affectedRegions": ["US Northeast", "Scandinavia", "UK National Grid", "Western Russia"],
        "economicImpact": "$200M",
        "description": "The largest solar flare of Solar Cycle 24, an X9.3 event, caused radio blackouts across the sunlit hemisphere and a subsequent G4 geomagnetic storm. GPS accuracy was degraded for hours. Puerto Rico's grid, already stressed, experienced additional strain shortly before Hurricane Maria.",
    },
    {
        "id": "nov-2004",
        "date": "2004-11-07",
        "name": "November 2004 Storm Series",
        "category": "G4",
        "peakKp": 8.0,
        "durationHours": 30,
        "affectedRegions": ["Scandinavia", "Western Russia", "UK National Grid", "Ontario Grid"],
        "economicImpact": "$300M",
        "description": "Following the Halloween 2003 storms, another series of strong flares produced sustained G4 conditions. Swedish and Norwegian grid operators enacted emergency load-shedding protocols. Transformers in Russia's western grid showed elevated GIC levels requiring protective shutdowns.",
    },
    {
        "id": "feb-1986",
        "date": "1986-02-08",
        "name": "February 1986 Moderate Storm",
        "category": "G3",
        "peakKp": 7.3,
        "durationHours": 15,
        "affectedRegions": ["US Northeast", "Quebec Grid", "Scandinavia"],
        "economicImpact": "$50M",
        "description": "A moderate G3 storm caused localized power fluctuations in the northeastern United States and Canada. Quebec's Hydro grid operators noted elevated GIC readings but avoided the widespread outage seen in 1989. The event spurred major investment in GIC monitoring infrastructure.",
    },
    {
        "id": "march-2015",
        "date": "2015-03-17",
        "name": "St. Patrick's Day Storm 2015",
        "category": "G4",
        "peakKp": 8.0,
        "durationHours": 24,
        "affectedRegions": ["US Northeast", "UK National Grid", "Scandinavia", "Ontario Grid"],
        "economicImpact": "$150M",
        "description": "The strongest storm of Solar Cycle 24 at the time, reaching G4 intensity. Named the St. Patrick's Day Storm, it caused auroras visible across the continental US. Grid operators in Scandinavia and the UK reported elevated transformer temperatures. GPS and HF radio were disrupted for approximately 12 hours.",
    },
    {
        "id": "aug-1972",
        "date": "1972-08-04",
        "name": "August 1972 Superflare",
        "category": "G5",
        "peakKp": 9.0,
        "durationHours": 20,
        "affectedRegions": ["US Midwest", "US Northeast", "Quebec Grid", "Scandinavia"],
        "economicImpact": "$150M (1972 USD)",
        "description": "An extremely fast CME reached Earth in just 14.6 hours — still a record. The resulting G5 storm disrupted AT&T's L4 coaxial cable telephone system across the US Midwest. Naval mines in Vietnam were inadvertently triggered by the magnetic disturbance. The event inspired early GIC research.",
    },
    {
        "id": "oct-2003-b",
        "date": "2003-10-30",
        "name": "Halloween X17 Flare Aftermath",
        "category": "G4",
        "peakKp": 7.8,
        "durationHours": 18,
        "affectedRegions": ["South Africa Grid", "Australia East Grid", "Japan Eastern Grid"],
        "economicImpact": "$800M (global)",
        "description": "The follow-on storm from the Halloween 2003 complex caused significant damage to power infrastructure in South Africa, where 14 large transformers were damaged — some permanently. The South African grid took months to fully recover, highlighting the vulnerability of mid-latitude grids to extreme events.",
    },
    {
        "id": "jan-2005",
        "date": "2005-01-17",
        "name": "January 2005 Particle Storm",
        "category": "G3",
        "peakKp": 7.0,
        "durationHours": 22,
        "affectedRegions": ["Scandinavia", "Western Russia", "UK National Grid"],
        "economicImpact": "$75M",
        "description": "A series of X-class flares in January 2005 produced one of the most intense solar proton events since 1989. While the geomagnetic storm itself was G3, the proton flux was extreme, causing satellite anomalies and polar cap absorption affecting aviation communications over high-latitude routes.",
    },
]