"""initial_schema

Revision ID: 14b3c76f8980
Revises: 
Create Date: 2026-04-09 11:16:03.705642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b3c76f8980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('plan_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_generated_at'), 'action_plans', ['generated_at'], unique=False)
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_index(op.f('ix_action_plans_region_id'), 'action_plans', ['region_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('symh_predicted', sa.Float(), nullable=False),
    sa.Column('storm_category', sa.Integer(), nullable=False),
    sa.Column('storm_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_generated_at'), 'forecasts', ['generated_at'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('solar_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proton_density', sa.Float(), nullable=False),
    sa.Column('sw_speed', sa.Float(), nullable=False),
    sa.Column('proton_temp', sa.Float(), nullable=False),
    sa.Column('bz_nT', sa.Float(), nullable=False),
    sa.Column('flow_pressure', sa.Float(), nullable=False),
    sa.Column('ae_index', sa.Float(), nullable=False),
    sa.Column('symh_index', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_readings_id'), 'solar_readings', ['id'], unique=False)
    op.create_index(op.f('ix_solar_readings_timestamp'), 'solar_readings', ['timestamp'], unique=True)
    op.create_table('region_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=50), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('line_km', sa.Integer(), nullable=False),
    sa.Column('age_factor', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_alerts_forecast_id'), 'region_alerts', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_region_alerts_id'), 'region_alerts', ['id'], unique=False)
    op.create_index('ix_region_alerts_region_created', 'region_alerts', ['region_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_region_alerts_region_id'), 'region_alerts', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_alerts_region_id'), table_name='region_alerts')
    op.drop_index('ix_region_alerts_region_created', table_name='region_alerts')
    op.drop_index(op.f('ix_region_alerts_id'), table_name='region_alerts')
    op.drop_index(op.f('ix_region_alerts_forecast_id'), table_name='region_alerts')
    op.drop_table('region_alerts')
    op.drop_index(op.f('ix_solar_readings_timestamp'), table_name='solar_readings')
    op.drop_index(op.f('ix_solar_readings_id'), table_name='solar_readings')
    op.drop_table('solar_readings')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_generated_at'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_action_plans_region_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_generated_at'), table_name='action_plans')
    op.drop_table('action_plans')
    # ### end Alembic commands ###
